/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-navy": "#1B3A6B",
        "action-blue": "#2563EB",
        "action-blue-hover": "#1D4ED8",
        "action-blue-active": "#1E40AF",
        "surface": "#FFFFFF",
        "surface-alt": "#F8FAFC",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container": "#eaedff",
        "surface-container-low": "#f2f3ff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dae2fd",
        "surface-tint": "#425e91",
        "surface-ai": "#F1F5F9",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "text-primary": "#0F172A",
        "text-secondary": "#475569",
        "text-muted": "#94A3B8",
        "border": "#E2E8F0",
        "border-strong": "#CBD5E1",
        "outline": "#747780",
        "outline-variant": "#c4c6d0",
        "success-green": "#16A34A",
        "success-surface": "#DCFCE7",
        "success-border": "#BBF7D0",
        "warning-amber": "#D97706",
        "warning-surface": "#FEF3C7",
        "warning-border": "#FDE68A",
        "significant-gap-orange": "#EA580C",
        "critical-red": "#DC2626",
        "critical-red-hover": "#B91C1C",
        "critical-surface": "#FEE2E2",
        "critical-border": "#FECACA",
        "primary": "#002452",
        "on-primary": "#ffffff",
        "primary-container": "#1b3a6b",
        "on-primary-container": "#89a5dd",
        "primary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#acc7ff",
        "on-primary-fixed": "#001a40",
        "on-primary-fixed-variant": "#294678",
        "secondary": "#0051d5",
        "on-secondary": "#ffffff",
        "secondary-container": "#316bf3",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary": "#002c0e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00451a",
        "on-tertiary-container": "#3bbc5f",
        "tertiary-fixed": "#7ffc97",
        "tertiary-fixed-dim": "#62df7d",
        "on-tertiary-fixed": "#002109",
        "on-tertiary-fixed-variant": "#005320",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#acc7ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      }
    }
  },
  plugins: [],
}
